backend:
  name: github
  repo: tele256/fotograma-website
  branch: main
  base_url: https://tele256.github.io
  auth_endpoint: /fotograma-website/admin/

media_folder: "src/assets/"
public_folder: "/src/assets/"

publish_mode: editorial_workflow

collections:
  - name: "posts"
    label: "Posts"
    folder: "src/content/"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Publish Date", name: "pubDate", widget: "datetime" }
      - { label: "Cover Image", name: "heroImage", widget: "image" }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Body", name: "body", widget: "markdown" }